name = "nh-legislative-tracker"
compatibility_date = "2023-12-01"
main = "src/workers/api-gateway.js"

# KV Namespaces
kv_namespaces = [
  { binding = "NH_LEGISLATIVE_DATA", id = "b4a09ada85cb42738d86e736adb9264a" },
  { binding = "NH_LEGISLATIVE_METADATA", id = "dbd12024b7f340e5a67b54ade88b6439" }
]

# Workers AI binding
[ai]
binding = "AI"

# Schedule for the data collection worker
[triggers]
crons = ["0 */4 * * *"] # Every 4 hours

# Environment variables
[vars]
ENVIRONMENT = "production"
NH_STATE_CODE = "nh"
VERSION = "1.0.0"

# Secrets that need to be set
# Run these commands to set up required secrets:
# wrangler secret put API_KEY
# wrangler secret put OPENSTATES_API_KEY

# Routes configuration
[[routes]]
pattern = "api.magafreenh.com/*"
zone_id = "b10403b29c9f3ad001ee29eca9616f57"

# Development configuration
[dev]
port = 8787
local_protocol = "http"
ip = "localhost"

# Build configuration
[build]
command = "npm run build"
watch_dir = "src"

# Worker size and limits
[limits]
cpu_ms = 50  # CPU time limit in ms (Unbound usage tier)
memory_mb = 128  # Memory limit in MB
log_retention_days = 30  # Days to retain logs

# Performance configuration
[performance]
kv_batch_size = 100  # Batch size for KV operations
force_https = true  # Force HTTPS

# Environment-specific configurations
[env.production]
route = "api.magafreenh.com/*"
kv_namespaces = [
  { binding = "NH_LEGISLATIVE_DATA", id = "b4a09ada85cb42738d86e736adb9264a" },
  { binding = "NH_LEGISLATIVE_METADATA", id = "dbd12024b7f340e5a67b54ade88b6439" }
]
vars = { ENVIRONMENT = "production" }
[env.production.observability]
enabled = true
head_sampling_rate = 1

[env.staging]
route = "staging-api.magafreenh.com/*"
kv_namespaces = [
  { binding = "NH_LEGISLATIVE_DATA", id = "b4a09ada85cb42738d86e736adb9264a" },
  { binding = "NH_LEGISLATIVE_METADATA", id = "dbd12024b7f340e5a67b54ade88b6439" }
]

# Use this simpler format for vars instead
vars.ENVIRONMENT = "staging"
vars.NH_STATE_CODE = "nh"
vars.VERSION = "1.0.0"

# Add AI binding for staging
[env.staging.ai]
binding = "AI"

[env.staging.observability]
enabled = true
head_sampling_rate = 1

[env.development]
vars = { ENVIRONMENT = "development" }

# Configure npm modules to bundle
[build.upload]
format = "modules"
main = "./src/workers/api-gateway.js"
dir = "./dist"

[observability.logs]
enabled = true